name = "tvddev"
type = "webpack"
account_id = "9108b97dd8df59ec46f276e892c7d76a"
workers_dev = false
routes = ["tvd.dev/*"]
zone_id = "348ab020bf346c816405e83e4406b235"

[site]
bucket = "output"
entry-point = "workers-site"

[env.thomasvandorencom]
routes = ["*.thomasvandoren.com/*", "thomasvandoren.com/*"]
zone_id = "cf9636219ddaf05d535f83868578703b"
